-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. CAMPAIGNS TABLE
create table public.campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  bank text,
  card_name text,     -- Mapped from 'cardName' in JSON
  category text,
  valid_until date,
  is_approved boolean default false,
  image text,
  url text,
  
  -- Additional fields for rich data
  slug text,
  brand text,
  offer text,         -- 'discount', 'earning' etc summary
  sector text,
  
  -- Metrics
  views integer default 0,
  clicks integer default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Index for faster filtering
create index campaigns_bank_idx on public.campaigns (bank);
create index campaigns_category_idx on public.campaigns (category);
create index campaigns_approved_idx on public.campaigns (is_approved);


-- 2. BANKS / SCRAPER CONFIG TABLE
-- Stores the configuration for banks and their cards (replacing localStorage 'scraper_config')
create table public.banks (
  id text primary key,  -- e.g. 'garanti', 'yapi-kredi'
  name text not null,
  logo text,
  config jsonb default '[]'::jsonb, -- Stores the cards array and scripts
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ADMIN MANAGEMENT TABLE
-- Stores admin users and their credentials securely
create table public.admin_users (
  id uuid default uuid_generate_v4() primary key,
  email text unique not null,
  name text not null,
  status text default 'pending' check (status in ('pending', 'active', 'rejected')),
  totp_secret text, -- Encrypted TOTP secret
  password_hash text, -- Hashed password
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  approved_by text,
  last_login timestamp with time zone
);

-- Index for faster admin lookups
create index admin_users_email_idx on public.admin_users (email);
create index admin_users_status_idx on public.admin_users (status);

-- Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.banks enable row level security;
alter table public.admin_users enable row level security;

-- POLICIES (Simple Public Access for MVP)
-- In a real app, you'd want authenticated-only writes.
-- For this "Admin Panel" relying on client-side secrets (or just obscurity for now):

-- READ: Everyone can read approved campaigns
create policy "Enable read access for all users" on public.campaigns
  for select using (true); 

-- WRITE: Allow all (since we control the admin panel via local env)
-- ideally restrict this to authenticated users later
create policy "Enable insert for all users" on public.campaigns for insert with check (true);
create policy "Enable update for all users" on public.campaigns for update using (true);
create policy "Enable delete for all users" on public.campaigns for delete using (true);

-- BANKS POLICIES
create policy "Enable items access for all users" on public.banks for select using (true);
create policy "Enable insert for all users" on public.banks for insert with check (true);
create policy "Enable update for all users" on public.banks for update using (true);
