-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. CAMPAIGNS TABLE
create table public.campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  bank text,
  card_name text,     -- Mapped from 'cardName' in JSON
  category text,
  valid_until date,
  is_approved boolean default false,
  image text,
  url text,
  
  -- Additional fields for rich data
  slug text,
  brand text,
  offer text,         -- 'discount', 'earning' etc summary
  sector text,
  
  -- Metrics
  views integer default 0,
  clicks integer default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Index for faster filtering
create index campaigns_bank_idx on public.campaigns (bank);
create index campaigns_category_idx on public.campaigns (category);
create index campaigns_approved_idx on public.campaigns (is_approved);


-- 2. BANKS / SCRAPER CONFIG TABLE
-- Stores the configuration for banks and their cards (replacing localStorage 'scraper_config')
create table public.banks (
  id text primary key,  -- e.g. 'garanti', 'yapi-kredi'
  name text not null,
  logo text,
  config jsonb default '[]'::jsonb, -- Stores the cards array and scripts
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ADMIN MANAGEMENT TABLE
-- Stores admin users and their credentials securely
create table public.admin_users (
  id uuid default uuid_generate_v4() primary key,
  email text unique not null,
  name text not null,
  status text default 'pending' check (status in ('pending', 'active', 'rejected')),
  totp_secret text, -- Encrypted TOTP secret
  password_hash text, -- Hashed password
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  approved_by text,
  last_login timestamp with time zone
);

-- Index for faster admin lookups
create index admin_users_email_idx on public.admin_users (email);
create index admin_users_status_idx on public.admin_users (status);

-- Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.banks enable row level security;
alter table public.admin_users enable row level security;

-- POLICIES (Simple Public Access for MVP)
-- In a real app, you'd want authenticated-only writes.
-- For this "Admin Panel" relying on client-side secrets (or just obscurity for now):

-- READ: Everyone can read approved campaigns
create policy "Enable read access for all users" on public.campaigns
  for select using (true); 

-- WRITE: Allow all (since we control the admin panel via local env)
-- ideally restrict this to authenticated users later
create policy "Enable insert for all users" on public.campaigns for insert with check (true);
create policy "Enable update for all users" on public.campaigns for update using (true);
create policy "Enable delete for all users" on public.campaigns for delete using (true);

-- BANKS POLICIES
create policy "Enable items access for all users" on public.banks for select using (true);
create policy "Enable insert for all users" on public.banks for insert with check (true);
create policy "Enable update for all users" on public.banks for update using (true);

-- 4. ADMIN INTEGRATIONS TABLE
-- Stores integration configurations (API keys, settings) for admin panel
create table public.admin_integrations (
  id text primary key default 'main', -- Single row for all integrations
  configs jsonb not null default '{}'::jsonb, -- All integration configs
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by text -- Admin email who made the change
);

-- Enable RLS for admin integrations
alter table public.admin_integrations enable row level security;

-- ADMIN INTEGRATIONS POLICIES
create policy "Enable read access for all users" on public.admin_integrations for select using (true);
create policy "Enable insert for all users" on public.admin_integrations for insert with check (true);
create policy "Enable update for all users" on public.admin_integrations for update using (true);

-- 5. ADMIN ACTIVITY LOGS TABLE
-- Stores admin activity logs for monitoring and auditing
create table public.admin_activity_logs (
  id text primary key default 'main', -- Single row for all logs
  logs jsonb not null default '[]'::jsonb, -- Array of activity log objects
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  total_count integer default 0 -- Total number of logs
);

-- Enable RLS for activity logs
alter table public.admin_activity_logs enable row level security;

-- ACTIVITY LOGS POLICIES
create policy "Enable read access for all users" on public.admin_activity_logs for select using (true);
create policy "Enable insert for all users" on public.admin_activity_logs for insert with check (true);
create policy "Enable update for all users" on public.admin_activity_logs for update using (true);

-- 6. ADMIN SECURITY SETTINGS TABLE
-- Stores security configuration and IP whitelist
create table public.admin_security_settings (
  id text primary key default 'main', -- Single row for all security settings
  settings jsonb not null default '{}'::jsonb, -- Security configuration
  ip_whitelist jsonb not null default '[]'::jsonb, -- IP whitelist array
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by text -- Admin email who made the change
);

-- Enable RLS for security settings
alter table public.admin_security_settings enable row level security;

-- SECURITY SETTINGS POLICIES
create policy "Enable read access for all users" on public.admin_security_settings for select using (true);
create policy "Enable insert for all users" on public.admin_security_settings for insert with check (true);
create policy "Enable update for all users" on public.admin_security_settings for update using (true);

-- 7. UNIVERSAL DATA TABLE
-- Single table for all admin panel data with automatic schema evolution
create table public.admin_universal_data (
  id text PRIMARY KEY,
  data_type text NOT NULL, -- e.g. 'admin_settings', 'admin_integrations', etc.
  data_content jsonb NOT NULL DEFAULT '{}'::jsonb, -- The actual data
  metadata jsonb DEFAULT '{}'::jsonb, -- Sync metadata, version info, etc.
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_by text, -- Admin email who made the change
  version integer DEFAULT 1, -- For versioning and conflict resolution
  is_active boolean DEFAULT true -- Soft delete support
);

-- Indexes for better performance
create index admin_universal_data_type_idx on public.admin_universal_data (data_type);
create index admin_universal_data_updated_at_idx on public.admin_universal_data (updated_at);
create index admin_universal_data_active_idx on public.admin_universal_data (is_active);
create index admin_universal_data_composite_idx on public.admin_universal_data (data_type, is_active, updated_at);

-- Enable RLS
alter table public.admin_universal_data enable row level security;

-- UNIVERSAL DATA POLICIES
create policy "Enable read access for all users" on public.admin_universal_data for select using (true);
create policy "Enable insert for all users" on public.admin_universal_data for insert with check (true);
create policy "Enable update for all users" on public.admin_universal_data for update using (true);
create policy "Enable delete for all users" on public.admin_universal_data for delete using (true);

-- Function to execute dynamic SQL (for auto table creation)
create or replace function exec_sql(sql text)
returns void
language plpgsql
security definer
as $$
begin
  execute sql;
end;
$$;
-- 8. APP VERSIONS TABLE
-- Stores application version history and current version
create table public.app_versions (
  id integer primary key default 1,
  current_version text not null default '3.0.0',
  version_history jsonb default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 1)
);

-- Enable RLS
alter table public.app_versions enable row level security;

-- Version policies
create policy "Enable read access for all users" on public.app_versions for select using (true);
create policy "Enable insert for all users" on public.app_versions for insert with check (true);
create policy "Enable update for all users" on public.app_versions for update using (true);

-- Insert default version record
insert into public.app_versions (id, current_version, version_history) 
values (1, '3.0.0', '[{"version":"3.0.0","date":"2025-01-01","changes":["Gerçek Zamanlı Senkronizasyon sistemi","Akıllı Kampanya Doğrulama sistemi","Dropdown menü yapısı","Modern admin paneli tasarımı","Email tabanlı admin sistemi","2FA güvenlik sistemi"],"type":"major"}]'::jsonb)
on conflict (id) do nothing;